name: Main

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck entrypoint.sh
      - uses: ./
        with:
          ignore: test

  test-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: lint
        continue-on-error: true
        uses: ./
        with:
          files: test/fail.md
          annotations: false
      - run: test "${{ steps.lint.outcome }}" == "failure"

  test-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          files: test/fail.md
          config: test/.markdownlint.json

  test-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          files: test/fix.md
          fix: true
      - run: test "$(md5sum test/fix.md)" == "d38a4c066f4c6e80a0409e23f68226bf  test/fix.md"

  pr-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint markdown
        id: pr-comment-lint
        continue-on-error: true
        uses: ./
        with:
          files: test/fail.md
          # config: test/.markdownlint.json
          pr_comment: true
      - name: pr-comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          MARKDOWN_LINT: ${{ steps.pr-comment-lint.outputs.MARKDOWNLINT_OUTPUT }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Markdown Linting')
            })

            const output = `#### Markdown Linting 🧹 📄 ✨\`${{ steps.pr-comment-lint.outcome }}\`

            <details><summary>Show Markdown Linting Results</summary>
            
            \`\`\`\n
            ${process.env.MARKDOWN_LINT
            \`\`\`
            
            </details>`;
            
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }